on:
  push:
    branches:
      - 'master'

name: Test

jobs:
  test-mac:
    name: Test macOS build
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-bundle
      - uses: actions-rs/cargo@v1
        with:
          command: bundle
          args: --release
  test-linux:
    name: Test Linux build
    runs-on: ubunto-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-bundle
      - uses: actions-rs/cargo@v1
        with:
          command: bundle
          args: --release
  test-wind:
    name: Test Windows build
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-bundle
      - uses: actions-rs/cargo@v1
        with:
          command: bundle
          args: --release
